---
- name: motd setting via Jinja2
  hosts: both
  tasks:
  - name: setting motd file from template
    template:
      src: motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
