---
- name: sshd setting
  hosts: all
  tasks:
  - name: not permitting root login with its password
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s+'
      line: PermitRootLogin without-password
      validate: sshd -t -f %s
    notify: restarting sshd
  handlers:
  - name: restarting sshd
    service:
      name: sshd
      state: restarted
  
      
