---
- name: wordpress環境構築
  hosts: database
#  remote_user: user
  become: yes
  vars:
    wordpress_url: https://ja.wordpress.org/wordpress-4.4.2-ja.tar.gz
 
  tasks:
  - name: 必要パッケージのyumインストール
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - firewalld
      - php
      - php-mysql
      - httpd
      - mariadb
      - mariadb-server
      - MySQL-python
  - name: firewalld up
    service:
      name: firewalld
      state: started
      enabled: True
 
  - name: firewalldでHTTPを許可
    firewalld:
      permanent: True
      service: http
      state: enabled
      immediate: True
 
 
  - name: wordpressのダウンロード
    get_url:
      url: "{{ wordpress_url }}"
      dest: /tmp/wordpress.tar.gz
 
  - name: タイムゾーンの設定
    ini_file: >
      dest=/etc/php.ini
      section=Date
      option=date.timezone
      value='"Asia/Tokyo"'
 
  - name: wordpressの展開
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      copy: no
 
  - name: wordpressの所有権をapacheに変更
    file:
      path: /var/www/html/wordpress/
      owner: apache
      group: apache
      recurse: yes
 
  - name: 各種サービスの再起動
    service:
      name: "{{item}}"
      state: started
      enabled: yes
    with_items:
      - mariadb
      - httpd
